name: Replatform Bitnami MongoDB Images with ARM64

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * FRI'

jobs:
  rebuild:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR (or Docker Hub)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse and replatform each tag
        env:
          SOURCE_IMAGE: bitnami/mongodb
          TARGET_IMAGE: ghcr.io/${{ github.repository_owner }}/containers/mongodb
          TAGS: '8.0,8.0-debian-12,latest'
        run: |
          IFS=',' read -ra TAG_ARRAY <<< "$TAGS"

          for TAG in "${TAG_ARRAY[@]}"; do
            echo "Processing tag: $TAG"

            # Pull existing amd64 image
            docker pull --platform linux/amd64 $SOURCE_IMAGE:$TAG

            # Create a temporary Dockerfile that just uses FROM
            echo "FROM --platform=\$BUILDPLATFORM $SOURCE_IMAGE:$TAG" > Dockerfile

            # Rebuild for arm64 and push multi-arch
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --tag $TARGET_IMAGE:$TAG \
              --push \
              .
          done
